In [1]:
import numpy as np

In [9]:
A=np.random.rand(3,2)
print(A)
B=A=np.random.rand(3,2)
print(B)

[[0.67375887 0.95543822]
 [0.39118742 0.68451088]
 [0.79385835 0.83620045]]
[[0.68886016 0.2944932 ]
 [0.54639553 0.18731511]
 [0.36010649 0.76808968]]


In [13]:
 C=[A,B]

In [14]:
print(C)

[array([[0.68886016, 0.2944932 ],
       [0.54639553, 0.18731511],
       [0.36010649, 0.76808968]]), array([[0.68886016, 0.2944932 ],
       [0.54639553, 0.18731511],
       [0.36010649, 0.76808968]])]


In [15]:
D=[A,C]

In [16]:
print(D)

[array([[0.68886016, 0.2944932 ],
       [0.54639553, 0.18731511],
       [0.36010649, 0.76808968]]), [array([[0.68886016, 0.2944932 ],
       [0.54639553, 0.18731511],
       [0.36010649, 0.76808968]]), array([[0.68886016, 0.2944932 ],
       [0.54639553, 0.18731511],
       [0.36010649, 0.76808968]])]]


In [18]:
X=np.stack((A,B), axis=0)

In [19]:
X.shape

(2, 3, 2)

In [ ]:
Y=np.stack((A,B), axis=0)

In [20]:
W=np.stack((A,X),axis=0)

ValueError: all input arrays must have the same shape

In [39]:
X[3,:,:]=np.random.rand(3,2)

IndexError: index 3 is out of bounds for axis 0 with size 2

In [31]:
X

array([[[0.68886016, 0.2944932 ],
        [0.54639553, 0.18731511],
        [0.36010649, 0.76808968]],

       [[0.72455293, 0.42100221],
        [0.8221328 , 0.04624719],
        [0.45159435, 0.60007222]]])

In [28]:
print(A)
print(B)

[[0.68886016 0.2944932 ]
 [0.54639553 0.18731511]
 [0.36010649 0.76808968]]
[[0.68886016 0.2944932 ]
 [0.54639553 0.18731511]
 [0.36010649 0.76808968]]


In [38]:
print(X)

[[[0.68886016 0.2944932 ]
  [0.54639553 0.18731511]
  [0.36010649 0.76808968]]

 [[0.88197052 0.72222502]
  [0.11216976 0.13688734]
  [0.67151677 0.55903991]]]


In [47]:
X_new=X[np.newaxis,:]

In [56]:
print(X.shape)
Y=np.expand_dims(X, axis=0)
print(Y.shape)

(2, 3, 2)
(1, 2, 3, 2)


In [53]:
X_new.shape

(1, 2, 3, 2)

In [57]:
A

array([[0.68886016, 0.2944932 ],
       [0.54639553, 0.18731511],
       [0.36010649, 0.76808968]])

In [58]:
B

array([[0.68886016, 0.2944932 ],
       [0.54639553, 0.18731511],
       [0.36010649, 0.76808968]])

In [67]:
Z=np.stack((A,B,A))

In [68]:
Z

array([[[0.68886016, 0.2944932 ],
        [0.54639553, 0.18731511],
        [0.36010649, 0.76808968]],

       [[0.68886016, 0.2944932 ],
        [0.54639553, 0.18731511],
        [0.36010649, 0.76808968]],

       [[0.68886016, 0.2944932 ],
        [0.54639553, 0.18731511],
        [0.36010649, 0.76808968]]])